version: "3"
services:
  proxy:
    image: "nginx:alpine"
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - 80:80
    environment:
      - NGINX_HOST=app.dev
      - NGINX_PORT=80
    volumes:
      - ./graphql/config/nginx.conf:/etc/nginx/conf.d/default.conf

  graphql:
    env_file:
      - ./graphql/.env
    build:
      context: .
      dockerfile: Dockerfile.graphql
    command: "npm start"
    image: "webapp:boiler"
    volumes:
      - ./graphql:/opt/src

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
