version: "3"
services:
  proxy:
    image: "nginx:alpine"
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - 80:80
    environment:
      - NGINX_HOST=app.dev
      - NGINX_PORT=80
    volumes:
      - ./web/config/nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: "npm start"
    image: "web:mhgu"
    volumes:
      - ./web:/opt/src

  graphql:
    env_file:
      - ./graphql/.env
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile.graphql
    command: "npm start"
    image: "graph:mhgu"
    volumes:
      - ./graphql:/opt/src
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
